server:
  port: 8092
  context-path: /

logging:
  level:
    root: INFO
    org:
      springframework:
        web: WARN
    io.swagger.models.parameters.AbstractSerializableParameter: error
theone:
  project:
    code: ycrb
    rootId: 0
    adminPath: admin
    accessDomain: http://img.ycfbapp.com/
  # custom elasticsearch configuration
  elasticsearch:
    index.name: ycrb_cms_article_index
    type: article
    ask.index.name: ycrb_cms_ask_index
    ask.type: ask
  file:
    types: gif,png,txt,jpg,jpeg
    image:
      size: 5242880
    media:
      size: 314572800
    temp: /home/nas/temp
  ad:
    url:
  adStats:
    url:
  httpUrl:
    newspager:
      list: http://vweb.people.cn/prod/common/paper/job/api/v1/newspaper/list?
      detail: http://vweb.people.cn/prod/common/paper/job/api/v1/newspaper/detail?
      date: http://vweb.people.cn/prod/common/paper/job/api/v1/newspaper/date?
    img: http://vimg.people.cn/prod/common/img/data/


spring:
  session:
    store-type: redis
  # datasource configuration
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.2.11:3306/ycrb_cms?useSSL=false&useUnicode\=true&characterEncoding\=utf-8
    username: admin
    password: nqD3WSpb
  # Api setting
  jackson:
    default-property-inclusion: non_empty
  # elasticsearch configuration
  data:
    elasticsearch:
      properties:
        host: 127.0.0.1
        port: 9300
      cluster-name: elasticsearch
  # file upload size configuration
  http:
    multipart:
      max-file-size: 300MB
      max-request-size: 600MB
  # redis configuration
  redis:
        database: 1
        host: 127.0.0.1
        password: p4y7aMXOrZAxzomB
        port: 6379
        pool:
            max-idle: 100
            min-idle: 1
            max-active: 1000
            max-wait: -1
        timeout: 3600
endpoints:
    enabled: false

aliyun:
  oss:
    bucket: rmrbpre
    mediaBucket: medias-source
    key: LTAINeFRLXjTKSlo
    secret: Ubmt44uMcPGfjsYAx6PFfeWoVdo8dh
    location: cn-beijing
    endpoint: http://oss-cn-beijing.aliyuncs.com/
    mediaEndpoint: http://medias-source.oss-cn-beijing.aliyuncs.com
    mnsEndpoint: http://1235141528253834.mns.cn-beijing.aliyuncs.com
    mtsEndpoint: http://mts.cn-beijing.aliyuncs.com
    directory: ycrb-dev/dir/
    videoDir: ycrb-dev/mp4Files/
    audioDir: ycrb-dev/mp3Files/
    queue: ycrb-dev
    url: http://rmrbpre.img-cn-beijing.aliyuncs.com/
    #文件上传分片的大小，阿里云上传文件时分片数量不能超过10000个，如果文件上传为10000MB，则分片大小不能低于1MB
    part.size: 512000

activitycode:
  domain: http://localhost:8090/api/
  appId:

gexin:
  appId: l8boXnMZPt9l3qudcA6Q21
  appKey: 5Mpu13WDon9XPiXLIvsLK4
  masterSecret: EREgY0LbJK9xe9sUpDu6U2
  url: http://sdk.open.api.igexin.com/apiex.htm

#极光推送配置
jpush:
    masterSecret: 98a7918ee199311fe4de0625
    appKey: e473736ee8640e0ab943c3cb

android:
  version: http://appuser.people.com.cn/i/views/version.json?pjcode=1_2017_02_70&devicetype=2

wechat:
  appId:
  appSecret:

# TODO (同步其他文件)
# 上传配置
upload:
  domain: ${theone.project.accessDomain}/
  useAliyun: true
  #TODO 图片上传路径 img/
  uploadBasePath:

# TODO (同步其他文件)http 接口交互
http:
  publiccms: http://10.50.162.40:8282/publiccms/
  sxh-api: http://127.0.0.1:8094/
  vshare: http://10.50.162.159:8999/#/
  ucenter: http://127.0.0.1:8096/