/*
根节点
*/
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (1, '顶级菜单', NULL, NULL, 'root', 0, '0,', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, 1);
/*
一级菜单
*/
-- 内容管理
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (3, '内容管理', 'cms.html', 'bars', 'cms', 1, '0,1,', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, 1);
-- 系统管理
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (4, '系统管理', 'sys.html', 'bars', 'sys', 1, '0,1,', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, 1);
-- 用户管理
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (5, '用户管理', 'users.html', 'bars', 'users', 1, '0,1,', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, 1);
-- 统计分析
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (6, '统计分析', 'analysis.html', 'bars', 'analysis', 1, '0,1,', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, 1);
-- 客户端管理
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (7, '客户端管理', 'client.html', 'bars', 'client', 1, '0,1,', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, 1);
-- 个人中心
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (8, '个人中心', 'myCenter.html', 'bars', 'myCenter', 1, '0,1,', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, 1);
--问政管理
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (64, '问政管理', 'ask.html', 'bars', 'ask', 1, '0,1,', NULL, NULL, NULL, NULL, 0, 30, NULL, NULL, 'cms:ask', 1);
--新闻爆料
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (68, '新闻爆料', '/news.html', 'bars', 'news', 1, '0,1,', 1, 1551949984224, 1, 1551949984224, 0, 30, NULL, NULL, NULL, 1);
/*
二级菜单
*/
/*3 内容管理*/
-- 栏目管理
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (9, '栏目管理', NULL, 'bars', 'category', 3, '0,1,3', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'cms:category', 1);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (10, '查看', NULL, '', 'category-view', 9, '0,1,3,9', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'cms:category:view', 0);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (11, '编辑', NULL, '', 'category-edit', 9, '0,1,3,9', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'cms:category:edit', 0);
-- 文章管理
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (12, '文章管理', NULL, 'bars', 'articles', 3, '0,1,3', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'cms:articles', 1);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (13, '查看', NULL, '', 'articles-view', 12, '0,1,3,12', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'cms:articles:view', 0);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (14, '编辑', NULL, '', 'articles-edit', 12, '0,1,3,12', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'cms:articles:edit', 0);
-- 评论管理
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (15, '评论管理', NULL, 'bars', 'comment', 3, '0,1,3', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'cms:comment', 1);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (16, '查看', NULL, '', 'comment-view', 15, '0,1,3,15', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'cms:comment:view', 0);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (17, '编辑', NULL, '', 'comment-edit', 15, '0,1,3,15', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'cms:comment:edit', 0);
-- 标签管理
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (62, '标签管理', NULL, 'bars', 'labelMenu', 3, '0,1,3,', 1, 1540194044905, 1, 1540194044905, 0, 40, NULL, NULL, 'cms:tags:view', 1);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (63, '编辑', NULL, NULL, 'edit', 62, '0,1,3,62,', 1, 1540194079805, 1, 1540194079805, 0, 30, NULL, NULL, 'cms:tags:edit', 0);

/*4 系统管理*/
-- 菜单管理
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (18, '菜单管理', NULL, 'bars', 'menu', 4, '0,1,4', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'sys:menu', 1);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (19, '查看', NULL, '', 'menu-view', 18, '0,1,4,18', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'sys:menu:view', 0);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (20, '编辑', NULL, '', 'menu-edit', 18, '0,1,4,18', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'sys:menu:edit', 0);
-- 字典管理
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (21, '字典管理', NULL, 'bars', 'dict', 4, '0,1,4', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'sys:dict', 1);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (22, '查看', NULL, '', 'dict-view', 21, '0,1,4,21', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'sys:dict:view', 0);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (23, '编辑', NULL, '', 'dict-edit', 21, '0,1,4,21', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'sys:dict:edit', 0);
/*5 用户管理*/
-- 机构管理
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (27, '机构管理', NULL, 'bars', 'office', 5, '0,1,5', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'users:office', 1);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (28, '查看', NULL, '', 'office-view', 27, '0,1,5,27', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'users:office:view', 0);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (29, '编辑', NULL, '', 'office-edit', 27, '0,1,5,27', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'users:office:edit', 0);
-- 用户管理
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (30, '用户管理', NULL, 'bars', 'user', 5, '0,1,5', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'users:user', 1);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (31, '查看', NULL, '', 'user-view', 30, '0,1,5,30', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'users:user:view', 0);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (32, '编辑', NULL, '', 'user-edit', 30, '0,1,5,30', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'users:user:edit', 0);
-- 角色管理
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (33, '角色管理', NULL, 'bars', 'role', 5, '0,1,5', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'users:role', 1);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (34, '查看', NULL, '', 'role-view', 33, '0,1,5,33', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'users:role:view', 0);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (35, '编辑', NULL, '', 'role-edit', 33, '0,1,5,33', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'users:role:edit', 0);
/*6 统计分析*/
-- 日志管理
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (36, '日志管理', NULL, 'bars', 'log', 6, '0,1,6', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'analysis:log', 1);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (37, '查看', NULL, '', 'log-view', 36, '0,1,6,36', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'analysis:log:view', 0);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (38, '编辑', NULL, '', 'log-edit', 36, '0,1,6,36', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'analysis:log:edit', 0);
-- 统计分析
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (39, '统计分析', NULL, 'bars', 'statistics', 6, '0,1,6', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'analysis:statistics', 1);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (40, '查看', NULL, '', 'statistics-view', 39, '0,1,6,39', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'analysis:statistics:view', 0);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (41, '编辑', NULL, '', 'statistics-edit', 39, '0,1,6,39', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'analysis:statistics:edit', 0);
-- 发稿量统计
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (72, '发稿量统计', NULL, 'bars', 'sending', 6, '0,1,6,', NULL, NULL, NULL, NULL, 0, 29, NULL, NULL, 'analysis:sending', 1);

/*7 客户端管理*/
-- 客户端菜单
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (42, '客户端菜单管理', NULL, 'bars', 'clientMenu', 7, '0,1,7', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'client:clientMenu', 1);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (43, '查看', NULL, '', 'clientMenu-view', 42, '0,1,7,42', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'client:clientMenu:view', 0);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (44, '编辑', NULL, '', 'clientMenu-edit', 42, '0,1,7,42', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'client:clientMenu:edit', 0);
-- 推送管理
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (45, '推送管理', NULL, 'bars', 'clientPush', 7, '0,1,7', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'client:clientPush', 1);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (46, '查看', NULL, '', 'clientPush-view', 45, '0,1,7,45', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'client:clientPush:view', 0);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (47, '编辑', NULL, '', 'clientPush-edit', 45, '0,1,7,45', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'client:clientPush:edit', 0);
-- 开屏图管理
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (48, '开屏图管理', NULL, 'bars', 'loadingImgs', 7, '0,1,7', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'client:loadingImgs', 1);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (49, '查看', NULL, '', 'loadingImgs-view', 48, '0,1,7,48', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'client:loadingImgs:view', 0);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (50, '编辑', NULL, '', 'loadingImgs-edit', 48, '0,1,7,48', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'client:loadingImgs:edit', 0);
-- 生活服务管理
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (51, '生活服务管理', NULL, 'bars', 'lifeService', 7, '0,1,7', NULL, NULL, NULL, NULL, 3, NULL, NULL, NULL, 'client:lifeService', 1);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (52, '查看', NULL, '', 'lifeService-view', 51, '0,1,7,51', NULL, NULL, NULL, NULL, 3, NULL, NULL, NULL, 'client:lifeService:view', 0);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (53, '编辑', NULL, '', 'lifeService-edit', 51, '0,1,7,51', NULL, NULL, NULL, NULL, 3, NULL, NULL, NULL, 'client:lifeService:edit', 0);
-- 邀请码管理
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (54, '邀请码管理', NULL, 'bars', 'activityCode', 7, '0,1,7', NULL, NULL, NULL, NULL, 3, NULL, NULL, NULL, 'client:activityCode', 1);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (55, '查看', NULL, '', 'activityCode-view', 54, '0,1,7,54', NULL, NULL, NULL, NULL, 3, NULL, NULL, NULL, 'client:activityCode:view', 0);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (56, '编辑', NULL, '', 'activityCode-edit', 54, '0,1,7,54', NULL, NULL, NULL, NULL, 3, NULL, NULL, NULL, 'client:activityCode:edit', 0);
-- 意见反馈
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (57, '意见反馈', NULL, 'bars', 'guestbook', 7, '0,1,7', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'client:guestbook', 1);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (58, '查看', NULL, '', 'guestbook-view', 57, '0,1,7,57', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'client:guestbook:view', 0);
INSERT INTO `sys_menu` (`id`, `name`, `href`, `icon`, `code`, `parent_id`, `parent_ids`, `create_by`, `create_at`, `update_by`, `update_at`, `del_flag`, `sort`, `target`, `resource_type`, `permission`, `is_show`) VALUES (59, '编辑', NULL, '', 'guestbook-edit', 57, '0,1,7,57', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'client:guestbook:edit', 0);
